env:
  app_version:       "2.0.0"
  repo_region:       "us-central1"
  project_id:        "quixotic-skill-380200"
  app_name:          "nodejs"
  tag_new_version:   "${GITHUB_SHA}"


name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

          
      - name: helm
        working-directory: "Charts/application"
        run: |
          terraform init 

      - name: Create workspace
        working-directory: "custom_helm_chart"
        run: |
          terraform workspace  select  ${{ env.environment }}   ||  terraform workspace  new  ${{ env.environment }}


      # Runs a set of commands using the runners shell
      - name: Deploy Application
        working-directory: "custom_helm_chart"
        run: |
          terraform apply   \
          -var repository="${{ env.repository }}"     \
          -var app_version="${{ env.app_version }}"   \
          -var app_port="${{ env.app_port }}"          \
          -var google_domain_name="${{ env.google_domain_name }}"          \
          -var app_name="${{ env.app_name }}"   \
          -var region="${{ env.region }}" \
          -var project_id="${{ secrets.PROJECT_ID }}" \
          -var environment="${{ env.environment }}" \
          --auto-approve

